### ISSUE TITLE
Numbers and Topic not being parsed correctly

### ISSUE THREAD

**Issue by zdhenard42** [zqtay/examtopics-scraper#1]
I noticed that the numbers such as Question number is not being parsed correctly from the API and is resulting in undefined even when it is present in the API response

**Comment by zqtay** [comment]
Can you share which exam is having this error?

**Comment by zdhenard42** [comment]
aws solutions architect 003

**Comment by zqtay** [comment]
This is because topic and question numbers were parsed from URL instead of returned HTML body. Has updated the code to parse from body instead.
