### ISSUE TITLE
difference in voting performance. 

### ISSUE THREAD

**Issue by johnakash** [zqtay/examtopics-scraper#5]
We are observing a true answer % difference in the scraper and in the original site. Please find the images below,
Question - https://www.examtopics.com/discussions/google/view/16998-exam-professional-cloud-security-engineer-topic-1-question/
![image](https://github.com/zqtay/examtopics-scraper/assets/1567281/bf6c8aef-fffe-4ca4-b240-a3ea30e07b63)

But in the scrapper the % is different. 
![image](https://github.com/zqtay/examtopics-scraper/assets/1567281/f1b88c68-6635-46d0-9169-1f9d087b9964)

Which one we need to use? Can you correct it?

**Comment by zqtay** [comment]
I am not able to replicate this.
![image](https://github.com/zqtay/examtopics-scraper/assets/45486751/90962220-52a5-4828-8c0b-63245d127705)
This is the .json file I get from scraping Google Cloud Security Engineer
[google-cloud-security-engineer-244.json](https://github.com/zqtay/examtopics-scraper/files/15244830/google-cloud-security-engineer-244.json)

**Comment by johnakash** [comment]
Interesting, I am not sure what went wrong. With the file which you have shared, it showing the same data as website.
