### ISSUE TITLE
Noticed the scraper is disabled even on locally hosted. 

### ISSUE THREAD

**Issue by zdhenard42** [zqtay/examtopics-scraper#6]
Seems to be a runtime error but when updating admin settings, the scraper remains disabled

**Comment by zqtay** [comment]
The new update requires Postgres database to store admin settings. It is possible that you encountered 500 due to `POSTGRES_PRISMA_URL` is not defined in `.env`.
I have pushed a workaround to store admin settings in global variable, so that a database is no longer required.

**Comment by zqtay** [comment]
@zdhenard42 Please verify if this has solved the issue.

**Comment by zdhenard42** [comment]
Thank you for the quick response! I am tied up with other tasks right now, but I will let you know this evening!

**Comment by zdhenard42** [comment]
Just confirmed it is working, thanks
